version: '3.7'  
services:
  db:
    image: mysql:5.7
    restart: on-failure
    ports: 
        - "3406:3306"
    environment:
        MYSQL_DATABASE: 'db_laravel6'
        # MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_ROOT_PASSWORD: "123"
        # Log in: db, root, 123
    volumes:
        - ./dbfiles:/var/lib/mysql
    command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
  
  app:
    build:
        context: .
        dockerfile: docker/Dockerfile
    image: 'laravel-6-essent'
    ports:
        - 8180:80
    volumes:
        - ./:/var/www/html

  adminer:           # имя контейнера
    image: adminer
    restart: on-failure
    ports:           # порт - локальный:внутри_контейнера
      - 6180:8080
    environment:
      ADMINER_DESIGN: rmsoft_blue # синее оформление

  # [1](https://bobcares.com/blog/docker-mailhog-sendmail/)
  # [6](https://blog.programster.org/mailhog)  
  mailhog:  
    image: mailhog/mailhog  
    ports:
      - "1025:1025" # порт SMTP   
      - "8025:8025" # порт веб-интерфейса MailHog  

  